### ISSUE TITLE
User story: post announcements

### ISSUE THREAD

**Issue by yicao928** [david-fisher/320-F19-Track-I#30]
It is the time apples are almost ripe. Steven wants to tell other growers, researchers and other people this good news and thanks to researchers. He opens OrchardWatch website and login to his account. At the research dashboard, there is a “new announcement” link. He selects the link and go to a new page which allows him to edit new announcement. There is a box with label "title" allows Steven to type title. Then Steven writes more words in the box under "title" with label "description". At the bottom of the description box, there is a picture icon. He clicks the icon and choose a photo from his phone or computer. There is a check mark with label "Share on Twitter". Because Steven also wants to share this message on Twitter, he checks this check mark. There is a grey line of words ”138/140”. After Steven continue typing a few words, the grey line turn to red to tell him the word limit is 140 words. After he writes everything he wants and add photos he wants, he clicks the "submit" button at right left corner. He goes back to the home page of OrchardWatch and see the announcement he wrote.
(For growers and researchers)

**Comment by khesemeyerumass** [comment]
Sean is a researcher who wants to post a new update about recent changes in the data he gathered. He uses his computer to open the OrchardWatch website and logs into his account. At the main page, Sean presses the “Announcements/Updates” button, which opens a new page. Since Sean is a researcher, he will have access to a “Make Announcement” button that will open up a new window. In the window, there will be a box for the title of the announcement, a larger box for a description/explanation for the post, a checkbox with the caption “Send Alert via Text”, another checkbox with the caption “Send Alert via Email”, and a “Post” button. Sean fills out the boxes and checks off the “Send Alert via Email” box. Once he clicks the “Post” button, the window disappears. After a few seconds, the page will be updated and his post will be displayed on the top of the list of announcements/updates. Also, since Sean checked the “Send Alert via Email” box, an email will be automatically sent to each account’s email address informing them about the new post. This feature will only be available to researchers and growers.
